import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import Providers from "@/app/providers";

const geist = Geist({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Watch shop | eCommerce',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={geist.className}>
        <head>
            <link rel="manifest" href="/site.webmanifest" />
            <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
            <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
            <link rel="stylesheet" href="/assets/css/flaticon.css" />
            <link rel="stylesheet" href="/assets/css/slicknav.css" />
            <link rel="stylesheet" href="/assets/css/animate.min.css" />
            <link rel="stylesheet" href="/assets/css/magnific-popup.css" />
            <link rel="stylesheet" href="/assets/css/fontawesome-all.min.css" />
            <link rel="stylesheet" href="/assets/css/themify-icons.css" />
            <link rel="stylesheet" href="/assets/css/slick.css" />
            <link rel="stylesheet" href="/assets/css/nice-select.css" />
            <link rel="stylesheet" href="/assets/css/style.css" />
        </head>
        <body>
        <Providers>{children}</Providers>

        {/* Core dependencies */}
        <Script src="/assets/js/vendor/modernizr-3.5.0.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/vendor/jquery-1.12.4.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/popper.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/bootstrap.min.js" strategy="afterInteractive" />

        {/* jQuery UI / menu / slider plugins – cần BEFORE main.js */}
        <Script src="/assets/js/jquery.slicknav.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/owl.carousel.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/slick.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/wow.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/animated.headline.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.magnific-popup.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.scrollUp.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.nice-select.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.sticky.js" strategy="afterInteractive" />

        {/* Form + validate (phải load TRƯỚC contact.js) */}
        <Script src="/assets/js/jquery.form.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.validate.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.ajaxchimp.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/mail-script.js" strategy="afterInteractive" />
        <Script src="/assets/js/contact.js" strategy="afterInteractive" />

        {/* Plugin wrapper & main init – luôn để cuối cùng */}
        <Script src="/assets/js/plugins.js" strategy="afterInteractive" />
        <Script src="/assets/js/main.js" strategy="afterInteractive" />
        </body>
        </html>
    );
}